### ISSUE TITLE
Changing and indexing prior factors after making graph

### ISSUE THREAD

**Issue by Nate711** [brentyi/jaxfg#11]
Thanks for the library! I'm trying to update the mu of a prior factor based on the optimized pose of another graph's node. However I'm stuck figuring out how the rows of graph.factor_stacks[1].factor.mu.unit_complex_xy correspond to which nodes. Any help? Thanks

**Comment by brentyi** [comment]
Hey!

The ordering of the stacked parameters should match the order that you passed the factors into `StackedFactorGraph.make(factors)`; row i should be the `mu` parameter of the i-th PriorFactor.

So if you break down `factors: List[FactorBase] = between_factors + prior_factors`, `prior_factors[i].mu.unit_complex_xy` should be equivalent to `graph.factor_stacks[1].factor.mu.unit_complex_xy[i, :]`.

Does that answer your question?

**Comment by Nate711** [comment]
Thanks for the quick reply I'll try it out

**Comment by Nate711** [comment]
And @brentyi , how are variables in the solution ordered? Are the variables ordered by the order of appearance in the factor list, or in the pose list passed into StackedFactorGraph.make? Or something else? Thanks

**Comment by brentyi** [comment]
The structure of the solution assignments will match the initial assignments (which needs to be explicitly passed into the `solve()` method), and the initial variable ordering of the assignments should parallel the factor ordering of the graph — it'll just respect whatever you pass into `VariableAssignments.make_from_defaults(some iterable)`, `VariableAssignments.make_from_dict(some dictionary)`, etc.

**Comment by Nate711** [comment]
Thanks!
