### ISSUE TITLE
A possible bug with the order in solution_assignments?

### ISSUE THREAD

**Issue by alecwangcq** [brentyi/jaxfg#14]
Hi Brent,

It seems that the `solution_assignments` is not consistent with the order of `pose_variables` in `pose_graph_simple.py`(https://github.com/brentyi/jaxfg/blob/f5204945bb6afa444810e6163e9a913bdbdd636b/scripts/pose_graph_simple.py). For the original code, the outputs of
```python
# Grab and print a single variable value at a time.
print("First pose (jaxlie.SE2 object):")
print(solution_assignments.get_value(pose_variables[0]))
print()

print("Second pose (jaxlie.SE2 object):")
print(solution_assignments.get_value(pose_variables[1]))
print()
```

was

```
First pose (jaxlie.SE2 object): 
SE2(unit_complex=[1. 0.], xy=[0.33333 0.     ])

Second pose (jaxlie.SE2 object):
SE2(unit_complex=[1. 0.], xy=[1.66667 0.     ])
```

However, if I change the code of creating  the factor graph to (switch the order of the two PriorFactors)

```python
factors: List[jaxfg.core.FactorBase] = [
jaxfg.geometry.PriorFactor.make(
        variable=pose_variables[1],
        mu=jaxlie.SE2.from_xy_theta(2.0, 0.0, 0.0),
        noise_model=jaxfg.noises.DiagonalGaussian(jnp.ones(3)),
    ),
    jaxfg.geometry.PriorFactor.make(
        variable=pose_variables[0],
        mu=jaxlie.SE2.from_xy_theta(0.0, 0.0, 0.0),
        noise_model=jaxfg.noises.DiagonalGaussian(jnp.ones(3)),
    ),
    jaxfg.geometry.BetweenFactor.make(
        variable_T_world_a=pose_variables[0],
        variable_T_world_b=pose_variables[1],
        T_a_b=jaxlie.SE2.from_xy_theta(1.0, 0.0, 0.0),
        noise_model=jaxfg.noises.DiagonalGaussian(jnp.ones(3)),
    ),
]
```

Then, the outputs become

```
First pose (jaxlie.SE2 object):
SE2(unit_complex=[1. 0.], xy=[1.66667 0.     ])

Second pose (jaxlie.SE2 object):
SE2(unit_complex=[1. 0.], xy=[0.33333 0.     ])
```

It seems that the order in the `solution_assignments` is determined by the order of the factors?

**Comment by brentyi** [comment]
Hi Chaoqi!

Can you try pulling from master and re-running this experiment? We *just* merged #13, which addresses this issue + introduces unit tests to check for regressions.

Apologies for the trouble, I realize that this is a fairly critical bug.

**Comment by alecwangcq** [comment]
I am using the repo cloned on Monday this week (03/28). I guess the repo has already be merged with https://github.com/brentyi/jaxfg/pull/13 at that time?

**Comment by brentyi** [comment]
#13 was merged yesterday (Tuesday 3/29), so I think it should fix your problem. I also just tried reproducing the error you pointed out and wasn't able to with the latest version on master.
