### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by shoyer** [brentyi/jaxfg#5]
Hi, this projects looks awesome! I definitely see some potential synergy/overlap with JAXopt: https://github.com/google/jaxopt

Would you consider adding an open source license so others can use your code? GitHub has some good guidance here:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository

Thanks!

**Comment by brentyi** [comment]
Hey thanks! JAXopt looks very interesting and relevant. And of course we both build on a lot of own your work on linear solvers for JAX, which I've been relying on very heavily.

I just added MIT licenses to this + every associated repository; appreciate the ping.

**Comment by shoyer** [comment]
much appreciated!
